nombre=input("Ingrese su nombre: ")
apellido=input("Ingrese su apellido: ")
edad=input("Ingrese su edad: ")
residencia=input("Ingrese su lugar de residencia: ")
print(f"Bienvenido {nombre} {apellido}, usted tiene {edad} años y vive en {residencia}")